### ISSUE TITLE
Incorrect order of arguments in usage information

### ISSUE THREAD

**Issue by bottomquark** [Bytekeeper/SpenderBender#1]
When running the program without arguments, it shows usage information
```
error: the following required arguments were not provided:
  --file-format <FILE_FORMAT>
  <FILE>

Usage: spenben --file-format <FILE_FORMAT> <FILE>
```
Sadly, the order of the parameters shown is incorrect. When running it this way:
```
target/debug/spenben  --file-format formats/dbk.toml 1081853796.csv 
Error: No such file or directory (os error 2)
```
Looks like the problem is line 136 of main.rs where args[1] is referenced for reading the file name.

Also, it would be great if the error message contained the file it tried to read

**Comment by Bytekeeper** [comment]
Should be fixed with the update yesterday, can you retry?

**Comment by bottomquark** [comment]
nice, thanks! Works fine
